### ISSUE TITLE
support for new webui from AUTOMATIC1111

### ISSUE THREAD

**Issue by 1blackbar** [imperator-maximus/stable-diffusion-krita#14]
PLugin doesnt work with new webui, and the one you have is outdated now and so new AUTOMATIC111 webui now refuses to take prompts, can you update the plugin ?

Endpoint: http://127.0.0.1:7860/api/, Reason: Traceback (most recent call last):
  File "C:\Users\BAZO\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 537, in getServerData
    with urllib.request.urlopen(req) as f:
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by imperator-maximus** [comment]
this plugin never worked with any WebUI because these have no API and AUTOMATIC1111 doesn't plan to make one. I made a ticket there but it was closed: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/65
We are looking forward for something better than any WebUI to switch over.
