### ISSUE TITLE
g-diffusion does not work on the latest colab or with the latest localhost api

### ISSUE THREAD

**Issue by i2chris** [imperator-maximus/stable-diffusion-krita#16]
On my local machine, the image returned is mostly nonsense. Are there specific settings for it? sampler etc?

On the colab it gives this error:
```
[2022-09-16 15:12:10,087] ERROR in app: Exception on /api/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "stable-diffusion-webui/api.py", line 245, in processAPI
    init_image, initmask=gdiffusion.get_init_image(initimg,0.99,1, 0)
  File "/content/stable-diffusion/stable-diffusion-webui/gdiffusion.py", line 86, in get_init_image
    np_mask_rgb, np_mask_rgb_dilated, mask_image=extract_mask(initimg)
  File "/content/stable-diffusion/stable-diffusion-webui/gdiffusion.py", line 49, in extract_mask
    blurred = skimage.filters.gaussian(np_mask_rgb_hardened[:], sigma=16., channel_axis=2, truncate=32.)
AttributeError: module 'skimage' has no attribute 'filters'
127.0.0.1 - - [16/Sep/2022 15:12:10] "POST /api/ HTTP/1.1" 500 -
```

**Comment by imperator-maximus** [comment]
sorry that this is not working. I will check- but we are waiting a huge update from developer of g-diffuser anyway. I think I will wait until this version has been finished.

**Comment by imperator-maximus** [comment]
should work now again but have to update to newest g-diffuser. This is also part of server.
