### ISSUE TITLE
[linux] txt2image and inpaint fails with AttributeError: 'SDParameters' object has no attribute 'strength'

### ISSUE THREAD

**Issue by lunaticstraydog** [imperator-maximus/stable-diffusion-krita#7]
Just installed beta3 version of the plugin, and txt2image fails clientside (on krita).  
Inpaint fails with same error.  
img2img works fine.
Full traceback below :
```
AttributeError
Python 3.10.6: /usr/bin/python3
Thu Sep  8 08:49:07 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py in TxtToImage()
  650         p.sampling_method=data["sampling_method"]
  651         p.cfg_value=data["cfg_value"]
  652         images = runSD(p)
  653         imageResultDialog( images,p)
  654 
images undefined
global runSD = <function runSD>
p = <stable_diffusion_krita.sd_main.SDParameters object>

 /home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py in runSD(p=<stable_diffusion_krita.sd_main.SDParameters object>)
  564         'batch_count': p.num, \
  565         'cfg_scale': p.cfg_value, \
  566         'denoising_strength': p.strength, \
  567         'seed':seed, \
  568         'height':SDConfig.height, \
p = <stable_diffusion_krita.sd_main.SDParameters object>
p.strength undefined
seed = -1
global SDConfig = <class 'stable_diffusion_krita.sd_main.SDConfig'>
SDConfig.height = 512
SDConfig.width = 512
AttributeError: 'SDParameters' object has no attribute 'strength'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'SDParameters' object has no attribute 'strength'",)
    name = 'strength'
    obj = <stable_diffusion_krita.sd_main.SDParameters object>
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py", line 652, in TxtToImage
    images = runSD(p)
  File "/home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py", line 566, in runSD
    'denoising_strength': p.strength, \
AttributeError: 'SDParameters' object has no attribute 'strength'

```

**Comment by lunaticstraydog** [comment]
Fix is easy enough: just need to add  p.strength=data["strength"] to both Inpainting() and TxtToImage() in if dlg.exec() part. (lines 642 and 756 of sd_main.py)
Attached is a fixed version of sd_main.py.
Thank you for the new version of the plugin, been enjoying it very much !
[sd_main.txt](https://github.com/imperator-maximus/stable-diffusion-krita/files/9524480/sd_main.txt)

(rename the file from sd_main.txt to sd_main.py)

**Comment by imperator-maximus** [comment]
download Beta 3.1 - this will also fix it as well. Thanks to @lunaticstraydog  for a quick fix :)
